### ISSUE TITLE
Players Self Reviving

### ISSUE THREAD

**Issue by Bitr0t-Zygzz** [KosmosisDire/TeammateRevive#11]
There are cases where a player who has been revived before is able to revive themselves on their original revive location.

Known Details:
- Revives on Original location, Where the skull originally was,
- There is no skull on the revive location (intended behavior) 
- Instant, (not sure if it was caused by death but its very likely as I was a glass cannon with 8 shaped glass)
- Happens not only to the host but also to other players.
- It is pretty fun to be revived but it might be immersion/game breaking for others.

Not sure if it happens all the time

**Comment by KosmosisDire** [comment]
Hmm okay, that sounds like a pretty easy fix. Sounds like I'm just not resetting something correctly. I'll see what I can find. Thanks!

**Comment by KosmosisDire** [comment]
Okay I published an update that should fix this issue! Thanks for reporting it, and sorry for the wait! Let me know if there are any other problems :)
