### ISSUE TITLE
Some sort of conflict with the ShowDeathCause mod

### ISSUE THREAD

**Issue by ZecChelovek** [KosmosisDire/TeammateRevive#13]
https://thunderstore.io/package/NotTsunami/ShowDeathCause/

Death messages with the amount of damage taken no longer appear except in very random and rare instances.

**Comment by KosmosisDire** [comment]
I don't really have any leads here and it seems pretty rare and niche so I'm gonna close this for now.

**Comment by KosmosisDire** [comment]
This should be fixed in the next update thanks to DestroyedClone.
