### ISSUE TITLE
Non-host cannot see anything to do with mod

### ISSUE THREAD

**Issue by SkyeMors** [KosmosisDire/TeammateRevive#14]
Was playing with a friend last night, and they kept telling me to go revive them, but the zone or skull or anything wasn't showing up on my end, only for them.

**Comment by KosmosisDire** [comment]
What stage were you on, and what other mods were you using, and how many runs had you played in a row without starting a new hosting session? It's definitely an edge case since it works pretty much all the time. I assume it has worked for you in the past?

**Comment by SkyeMors** [comment]
Stage 2, about 124 other mods (admittedly probably what's causing it), first run of the night, first run after installing the mod, and it didn't show up in the five runs after that.
I mean if you or someone you know can end up finding whatever mod is messing up Multiplayer stuff... I went through and enabled/disabled mods, and wasn't able to get it to show up or fix the desync'd issues. I also have visual discrepancies in the shop (probably due to the Bazaar Expanded mod or whatever).

Current modlist: za6VzQtHD7

**Comment by KosmosisDire** [comment]
I am gonna close this just because it most certainly a problem with another mod. I don't have time to look through everything but feel free to open another issue if you find the problem.
