### ISSUE TITLE
People with Transcendence can instantly revive other teammates.

### ISSUE THREAD

**Issue by gavingg12** [KosmosisDire/TeammateRevive#15]
Title. Whenever you have transcendence, you can simply walk over somebody and instantly revive them.

**Comment by ContraMods** [comment]
Agreed. I assume it's because you have 1 HP, and that fulfills the HP% leech requirement. I guess that could be another reason to use Transcendence on your build lol. If anything this should be a config option.

**Comment by gavingg12** [comment]
Tbh, I can't think of a way to fix this other than making it revive slower the lower health you have.

(Also, it should be a config to go on %hp OR set amount of hp, as well has the amount of hp you need)

**Comment by KosmosisDire** [comment]
I am planning on making the revive take a certain amount of time, and then making it so you lose a percentage of health over that time period. This might help with this problem. Mainly I am super busy with school at the moment so I don't have time to do stuff but I am open to PRs

**Comment by KosmosisDire** [comment]
This will be fixed in the next update so stay tuned!

**Comment by KosmosisDire** [comment]
This should be fixed now
