### ISSUE TITLE
Not working after DLC update

### ISSUE THREAD

**Issue by EndlessEden** [KosmosisDire/TeammateRevive#24]
After the most recent update to ROR2 following the DLC release, this has stopped working.

**Comment by nathanpovo** [comment]
@KosmosisDire I would be happy to help to fix this issue

**Comment by KosmosisDire** [comment]
Hey yeah I figured this would happen. @amadare42 any thoughts here?
@nathanpovo Thank you! I would certainly accept any pull requests :)

**Comment by amadare42** [comment]
@nathanpovo please let me know if you started working on it, so we could avoid work duplication. Thanks.

**Comment by nathanpovo** [comment]
> @nathanpovo please let me know if you started working on it, so we could avoid work duplication. Thanks.

I only started to get the project setup on my local machine.

I don't have a lot of experience with working with bepinex plugins so I'll probably be a little slow to get this done; feel free to work on this if you know it'll be a quick job.

**Comment by EndlessEden** [comment]
just wanted to add, i compiled the draft to see if i could give any info. (ran SP run, as my partner which is willing to test with me is unavailable till later)

Log shows only this:

`[Error: Unity Log] TypeLoadException: Could not load type of field 'TeammateRevive.Skull.SkullTracker:skulls' (4) due to: Could not load file or assembly 'UnityEngine.Networking, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. assembly:UnityEngine.Networking, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null type:<unknown type> member:(null)`

Skull doesn't show, will test further ASAP in MP. (I can test, if further changes are submitted to the draft)

**Comment by amadare42** [comment]
@EndlessEden @nathanpovo As per my preliminary testing, looks like developers moved Unity.Networking namespace to different binary named `com.unity.multiplayer-hlapi.Runtime.dll`. That is probably source of the issue because no Unity.Networking reference is binary compatible with that. 
So I would suggest removing reference to Unity.Networking and use com.unity.multiplayer-hlapi.Runtime.dll binary instead.

**Comment by EndlessEden** [comment]
@amadare42 Please disregard my earlier reply.

Tested with correct branch, functioned as expected; Perfectly. - Will do a full-game later and will reply if any unexpected log entries.

**Comment by KosmosisDire** [comment]
@EndlessEden Mod has been updated successfully! Thanks @nathanpovo for your work it was incredibly helpful

**Comment by KosmosisDire** [comment]
Let us know if there are any other problems :)
