### ISSUE TITLE
Version without death curse option.

### ISSUE THREAD

**Issue by Lumby** [KosmosisDire/TeammateRevive#33]
**Is your feature request related to a problem? If so, please describe.**
This is the teammate revival mod that I find the most appealing, but I don't like how it adds extra items to the logbook even without Death Curse mode enabled.

**Describe the feature you'd like**
A version of the mod that doesn't include Death Curse mode, or otherwise doesn't add extra items and inflate the logbook.

**Describe alternatives you've considered**

**Additional context**

**Comment by breadguy69** [comment]
I'd like to request the ability to remove the artifact from the lobby too, for the sake of my ocd lol

**Comment by KosmosisDire** [comment]
We will likely make the toggle turn off the artifact as well. Some 3rd party mods might still turn on the artifact in some cases, but the toggle will remove the game mode visually from any menus.

**Comment by KosmosisDire** [comment]
This is now in the latest release, you have to restart the game for the option to take effect after you turn in on. Thanks for submitting your idea!

**Comment by KosmosisDire** [comment]
So we have reports this isn't working. @breadguy69 can you try turning it off via the r2modman config (rather than in-lobby config) if you haven't already. Also make sure you turn off  **_both_** toggles

**Comment by KosmosisDire** [comment]
@breadguy69 sorry, I have talked to amadare, and this is also not working for us. We'll try to get it patched and working soon

**Comment by KosmosisDire** [comment]
This should be fixed
