### ISSUE TITLE
Game won't load with both TeammateRevive and ExtendedLoadout

### ISSUE THREAD

**Issue by JamesMDenton** [KosmosisDire/TeammateRevive#35]
Game won't load with both TeammateRevive and [ExtendedLoadout](https://thunderstore.io/package/KingEnderBrine/ExtendedLoadout/) by [KingEnderBrine](https://thunderstore.io/package/KingEnderBrine/). [Crossposting from their github.](https://github.com/KingEnderBrine/-RoR2-ExtendedLoadout/issues/6)

> Looks like it's a conflict with [TeammateRevival](https://thunderstore.io/package/KosmosisDire/TeammateRevival/) by [KosmosisDire](https://thunderstore.io/package/KosmosisDire/). Modlist with either loads fine. Only happens when both are enabled. I'm crossposting this to their github, not sure who the conflict is on.
> 
> ```
> [Info   :     R2API] Generating a total of 3 ContentPacks...
> [Info   : Unity Log] LoadContentPacks() start
> [Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
> Stack trace:
> TeammateRevive.ContentManager.LanguageOnSetStringByToken (On.RoR2.Language+orig_SetStringByToken orig, RoR2.Language self, System.String token, System.String localizedstring) (at <aeb998a1ba114dbfa5c12346a5ba4503>:0)
> DMD<>?-1506757376.Hook<RoR2.Language::SetStringByToken>?-506429568 (RoR2.Language , System.String , System.String ) (at <bc93fda088a84295a80156884a099bc5>:0)
> RoR2.Language.SetStringsByTokens (System.Collections.Generic.IEnumerable`1[T] tokenPairs) (at <0f44b36eaa194934bb127b3fdd08e444>:0)
> RoR2.Language.LoadStrings () (at <0f44b36eaa194934bb127b3fdd08e444>:0)
> ExtendedLoadout.ExtendedLoadoutPlugin+<RoR2-ContentManagement-IContentPackProvider-LoadStaticContentAsync>d__24.MoveNext () (at <35a5c033de22407ba2ed9881b6f6d4e6>:0)
> HG.Coroutines.ParallelProgressCoroutine+<InternalCoroutine>d__13.MoveNext () (at <252b0f5a2f1d4671be7eac97451a1156>:0)
> HG.Coroutines.ParallelProgressCoroutine.MoveNext () (at <252b0f5a2f1d4671be7eac97451a1156>:0)
> RoR2.RoR2Application+<LoadGameContent>d__70.MoveNext () (at <0f44b36eaa194934bb127b3fdd08e444>:0)
> UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <469e86e97fa2467ebffe49bbd6086325>:0)
> ```

**Comment by KosmosisDire** [comment]
This is a known issue and has been fixed. Development is a bit slow right now since I'm in school but whenever it's updated next this will be fixed. I'll try to get it out as soon as possible, but I can't really guarantee any time.

Thank you for the report!

**Comment by JamesMDenton** [comment]
Oh awesome, thanks. Great mod, awesome work! =)

**Comment by KosmosisDire** [comment]
This is now fixed in the latest release! Thanks for reporting :)
