### ISSUE TITLE
Death Curse Mechanic items spawning when not enabled, causing lost items/wasted purchases.

### ISSUE THREAD

**Issue by TheGam1ngWizard** [KosmosisDire/TeammateRevive#51]
**Describe the bug**
Death Curse Mechanic items spawning when not enabled, causing lost items/wasted purchases.

**To Reproduce**
Start Classic/Simulacrum game, find items, some are Death Curse items that disappear on pickup.

**Expected behavior**
Items either don't appear, or they turn into scrap on pick-up to make purchase not wasted.

**Comment by KosmosisDire** [comment]
Hi, this should be fixed in the next update. I will release it today.

**Comment by TheGam1ngWizard** [comment]
Thanks for the quick update!

**Comment by KosmosisDire** [comment]
Okay it is released, thanks for reporting this, and please let me know if the issue persists. I am closing this for now.
