### ISSUE TITLE
Dead Man's Hand still spawns even when "Hide Death Curse mode items" is set to True

### ISSUE THREAD

**Issue by Caboose12000** [KosmosisDire/TeammateRevive#55]
I'm not sure if this is a true bug or an intended feature, but the Lunar item "Dead Man's Hand" effectively cannot be disabled.  Despite it being hidden from the log book when "Hide Death Curse mode items in logbook" is enabled, it still drops / spawns in lunar shops during a run.  Even when "Hide Death Curse Artifact" is enabled, it still spawns.

I'm not sure what other info I can provide to be helpful, but let me know if there's anything I can do (Caboose12000#3908).  Thanks!

**Comment by KosmosisDire** [comment]
Thanks, I'll look into it and get back to you if I have any questions

**Comment by KosmosisDire** [comment]
is this option enabled by any chance in the config?
![image](https://user-images.githubusercontent.com/39423700/166837549-047c2a5b-1de9-43e2-80a8-a9cc2b3354f5.png)

**Comment by KosmosisDire** [comment]
Okay this is fixed and should be out when the next update is released

**Comment by Caboose12000** [comment]
Sorry I was away at dinner, thanks for the fix!
