### ISSUE TITLE
Respawn items (Dio's, Void Heart from Aetherium) still leave a totem

### ISSUE THREAD

**Issue by gaforb** [KosmosisDire/TeammateRevive#6]
Totem works and can respawn an already alive player at full health

**Comment by KosmosisDire** [comment]
You're saying when a player is revived by some other mod, the skull stays and can be used to "revive" a player again even though they are alive?

**Comment by KosmosisDire** [comment]
Yeah actually that would make sense and I didn't think of that. Once I get the damage numbers and lighting synced over the network, I'll start working on a fix for this. Thank you!

**Comment by gaforb** [comment]
Happens with both modded and unmodded respawn methods. As a suggestion, maybe a (configurable) timer for how long before the skull / respawn area spawns, which checks a second time that the player is dead?

**Comment by KosmosisDire** [comment]
I think that would still fail for mods where the player revives after the skull has spawned. I am already looping through each dead player and I can just check if they are still dead each time (Should be a very simple check). If they aren't then I'll just despawn the skull and move them back to the alive players.

**Comment by KosmosisDire** [comment]
The timer idea though would be good just in general. In case players want there to be a wait, instead of being able to immediately revive other players

**Comment by KosmosisDire** [comment]
Okay, this should be fixed in the latest update! File another issue if there's still anything wrong :)
