### ISSUE TITLE
Totem not spawning after first level of first run (ver. 3.3.4)

### ISSUE THREAD

**Issue by spindocks** [KosmosisDire/TeammateRevive#8]
When playing on a lobby with 5 members (using toomanyfriends) the totem never spawns and disallows the ability to revive. Tried on a 2 player lobby and still the same result; no totem so no ability to revive. 

Here is my mod list:
![thingformod](https://user-images.githubusercontent.com/80333274/126918880-afa0b48a-3138-4de0-94f6-2e99600983df.PNG)

Here is my log output:
[logformod.txt](https://github.com/KosmosisDire/TeammateRevive/files/6874824/logformod.txt)

I will be available for the rest of the night if there are any questions and/or requests for more resources.

**Comment by KosmosisDire** [comment]
Yeah I have been trying to figure this out as it seems to be working for me in my testing but not for other people. I think it's not a problem with toomanyfriends tho. As for the logs it doesn't look like the players got set up at all. We're you the host? Since the mod is mostly server-side you have to be the host to see most of the logging. Also you have to turn on logging in the config. If you want to you can turn on file logging and that will log only the logs for my mod into a .txt file

**Comment by spindocks** [comment]
I did not have logging turned on in the config. I was the host. I can do another test when one of my pals get back from eating with the logs on.

**Comment by KosmosisDire** [comment]
Okay cool, and thanks

**Comment by spindocks** [comment]
Here it is, tell me if I did it wrong I'm still a bit new to log outputs haha :
[log for mod2.txt](https://github.com/KosmosisDire/TeammateRevive/files/6874941/log.for.mod2.txt)

We tried twice because the first time I had a suspicious encounter where it did in fact work but when we pressed "continue" after dying my friend got kicked from the game. Second time through it worked like above, though, no totem so no revive. (The first time through I was the one to die first, the second time through they were. Maybe it's host based? In all the games where we used it I wasn't the first to die.)

**Comment by KosmosisDire** [comment]
Hmmm... It looks like nothing logged again. Check the logging again. But also maybe turn on file logging cause it easy to see if it's working or not. If you can't get it to work don't stress

**Comment by KosmosisDire** [comment]
Those are good observations though, and I'll check it out as much as I can

**Comment by spindocks** [comment]
I'll give it another go with file logging in a bit, expect it in an hour or so

**Comment by KosmosisDire** [comment]
Okay, just make sure that once you start the game you can find the .txt
file. If it's there then you know it's working and you can continue
testing. Just in case, I wouldn't want you to finish testing and realize
it's not there hehe

**Comment by spindocks** [comment]
Here is the console log again, just incase (I realized that r2mm didn't actually save my config presets):
[consolelog.txt](https://github.com/KosmosisDire/TeammateRevive/files/6875421/consolelog.txt)

And, here is the file log:
[filelog.txt](https://github.com/KosmosisDire/TeammateRevive/files/6875422/filelog.txt)

Again, in the first session I (spin) died and the skull did actually spawn, followed by my friend (jubin) dying and the skull for them also spawning. However, in the second session they spawned first and the skull did not spawn, and then when I died the skull did not spawn either. I was the host, so (with my lack of coding skills) I feel like this could be related to networking. The log says that the skull spawns during both sessions but it does not on the second.

**Comment by KosmosisDire** [comment]
Okay that's very helpful. Out of which of those four times that you died did the skull spawn?

**Comment by KosmosisDire** [comment]
Oh wait I didn't finish your comment lol nvm

**Comment by spindocks** [comment]
> Okay that's very helpful. Out of which of those four times that you died did the skull spawn?

The first two times during the file log.
[Info] -  Setup Teammate Revival  - 7/25/2021 11:41:42 PM

[Info] -  Num Players - 1  - 7/25/2021 11:44:50 PM

[Info] -  spin added.  - 7/25/2021 11:45:02 PM

[Info] -  jubin added.  - 7/25/2021 11:45:02 PM

[Info] -  spin Setup  - 7/25/2021 11:45:03 PM

[Info] -  jubin Setup  - 7/25/2021 11:45:04 PM

[Info] -  All Players Setup Succesfully  - 7/25/2021 11:45:04 PM

[Info] -  Skull spawned on Server and Client  - 7/25/2021 11:45:31 PM

[Info] -  spin Died!  - 7/25/2021 11:45:31 PM

[Info] -  Skull spawned on Server and Client  - 7/25/2021 11:45:58 PM

[Info] -  jubin Died!  - 7/25/2021 11:45:58 PM

[Info] -  Game Over - reseting data  - 7/25/2021 11:45:58 PM

both of these deaths, sorry for the wall.

**Comment by spindocks** [comment]
> Oh wait I didn't finish your comment lol nvm

oh whoops lol

**Comment by KosmosisDire** [comment]
Okay yeah that makes sense. I think I figured it out!! I have a list of alive players and dead players. and int he last few updates I added a list of all players. But I forgot to reset the allplayers list between stages and runs so it just keeps adding duplicate players. That means that on the second run there are two players that dont actually exist and it's messing it all up. I'll fix that and push a new update (It might take a little bit). Let me know if that fixes it when you can, and I can close this issue!

**Comment by spindocks** [comment]
I'd also recommend double checking the issue of the client dying first. It's interesting that that was happening but in serious runs we did with 5 members if one of us (other than me) died no totem would spawn. This was without playing other runs so this player list issue wouldn't have any interference.

**Comment by spindocks** [comment]
> I'd also recommend double checking the issue of the client dying first. It's interesting that that was happening but in serious runs we did with 5 members if one of us (other than me) died no totem would spawn. This was without playing other runs so this player list issue wouldn't have any interference.

I could maybe run a test with the client dying first but that would be awhile, sorry.

**Comment by KosmosisDire** [comment]
The problem also happens when it loads a new stage (but in your particular test you didn't go to the second stage). So it should technically work on the first stage of the first run all the time. Then after that it wont work

**Comment by spindocks** [comment]
Ohh, I see. That makes sense. First death was on stage 3 so that checks out. Glad to know we got it resolved, it's a very neat mod idea.

**Comment by KosmosisDire** [comment]
Thanks! :) And thank you for taking the time to submit an issue! I really appreciate it! Hopefully this fix works

**Comment by KosmosisDire** [comment]
I pushed the update, so if there are still problems go ahead and post another issue
